setwd("~/repositories/r_tutorial/bootcamp-2019")

source(here::here('data/day3_objects.R'))

library(ggthemes)
library(data.table)

ggplot(gapminder07) +
  geom_point(aes(x = gdpPercap, y = lifeExp)) + 
  labs(title = 'Relationship between life expectency and GDP per capita', 
       x = 'GDP per capita', 
       y = 'Life expectency',
       caption = 'This is a caption',
       subtitle = 'woah') +
  theme_few()


gapminder07 <- as.data.table(gapminder07)
gapminder07[, log_pop := log(pop)]
gapminder07[, log_gdpPercap := log(gdpPercap)]

ggplot(gapminder07) +
  geom_point(aes(x = log_pop, y = log_gdpPercap)) +
  labs(title = 'Log GDP as a function of Log Population',
       x = 'LN Population',
       y = 'LN GDP per capita') + 
  theme_few()

#exercise: total energy (all sources) generated over time

#create variable for total energy at t=t1

long_gen %>%
  group_by(datetime) %>%
  summarize(output = sum(output)) %>%
  ggplot() +
  geom_col(aes(x = datetime, y = output)) +
  labs(title = 'Total energy generated, by hour', x = 'Hour', y = 'Output (MW)') +
  theme_few()


#column plot of hydro generated over time

long_gen %>%
  filter(source %in% c('large_hydro', 'small_hydro')) %>%
  group_by(datetime) %>%
  summarize(output = sum(output)) %>%
  ggplot() +
  geom_col(aes(x = datetime, y = output), color = 'blue') +
  labs(title = 'Total hydro generation, by hour', x = 'Hour', y = 'Hydro output (MW)') + 
  theme_few()

long_gen %>%
  filter(source %in% c('large_hydro', 'small_hydro')) %>%
  group_by(datetime) %>%
  summarize(output = sum(output)) %>%
  ggplot() +
  geom_line(aes(x = datetime, y = output), size = 1.5, col = 'darkred') +
  labs(title = 'Total hydro generation, by hour', x = 'Hour', y = 'Hydro output (MW)') + 
  theme_few()


long_gen %>%
  filter(source %in% c('large_hydro', 'small_hydro')) %>%
  group_by(datetime) %>%
  summarize(output = sum(output)) %>%
  ggplot() +
  geom_area(aes(x = datetime, y = output), size = 1.5, col = 'pink', fill = 'grey') +
  labs(title = 'Total hydro generation, by hour', x = 'Hour', y = 'Hydro output (MW)') + 
  theme_few()

long_gen %>% #standard is 1.5x SD outside mean
  ggplot() + 
  geom_boxplot(aes(x = source, y = output)) + 
  labs(title = 'Amount of energy generated by each source, Sep 3--9', x = 'Source') +
  theme_few()

long_gen %>%
  filter(source == 'large_hydro') %>%
  ggplot() +
  geom_line(aes(x = datetime, y = output), color = 'turquoise') +
  geom_smooth(aes(x = datetime, y = output)) +
  labs(title = 'Hydo (large) generation per hour, Sep 3--9', x = 'Hour') +
  theme_few()

long_gen %>%
  group_by(datetime) %>%
  summarize(mean_output = mean(output)) %>%
  ggplot() +
  geom_line(aes(x = datetime, color = source, y = output)) +
  labs(x = 'Hour', y = 'Output', color = 'Power source') +
  geom_line(aes(x = datetime, y = mean_output)) +
  theme_few()



long_gen %>%
  group_by(source) %>%
  summarize(output = sum(output)) %>%
  ggplot() +
  geom_col(aes(x = source, y = output), fill = 'grey') +
  geom_hline(aes(yintercept = mean(output)), color = 'blue') +
  geom_hline(aes(yintercept = median(output)), color = 'orange') +
  labs(x = 'Source', y = 'Output') +
  theme_few()



imports %>%
  ggplot() + 
  geom_line(aes(x=datetime, y=imports), col="blue") + 
  scale_x_datetime(date_labels="%H:%M", date_breaks="12 hours") +
  labs(title="Energy imports over time in California", 
       subtitle="Hourly data from September 3-9, 2018", 
       x="Hour", y="Amount imported (MW)") +
  theme_few() +
  theme(axis.text.x = element_text(angle = 45))

long_gen %>%
  filter(source %in% c('wind', 'solar', 'geothermal')) %>%
  ggplot() +
  geom_line(aes(x = datetime, y = output, color = source), size = 1) +
  scale_color_brewer(palette = 'Dark2', name = 'Energy source') +
  theme_few()


'
theme_name <- function (){
  them_few %replace%
    theme() #theme arguments
}
'




