setwd("~/repositories/r_tutorial/bootcamp-2019")

source(here::here('data/day3_objects.R'))

library(ggthemes)
library(data.table)

ggplot(gapminder07) +
  geom_point(aes(x = gdpPercap, y = lifeExp)) + 
  labs(title = 'Relationship between life expectency and GDP per capita', 
       x = 'GDP per capita', 
       y = 'Life expectency',
       caption = 'This is a caption',
       subtitle = 'woah') +
  theme_few()


gapminder07 <- as.data.table(gapminder07)
gapminder07[, log_pop := log(pop)]
gapminder07[, log_gdpPercap := log(gdpPercap)]

ggplot(gapminder07) +
  geom_point(aes(x = log_pop, y = log_gdpPercap)) +
  labs(title = 'Log GDP as a function of Log Population',
       x = 'LN Population',
       y = 'LN GDP per capita') + 
  theme_few()

#exercise: total energy (all sources) generated over time

#create variable for total energy at t=t1

long_gen %>%
  group_by(datetime) %>%
  summarize(output = sum(output)) %>%
  ggplot() +
  geom_col(aes(x = datetime, y = output)) +
  labs(title = 'Total energy generated, by hour', x = 'Hour', y = 'Output (MW)') +
  theme_few()


#column plot of hydro generated over time

long_gen %>%
  filter(source %in% c('large_hydro', 'small_hydro')) %>%
  group_by(datetime) %>%
  summarize(output = sum(output)) %>%
  ggplot() +
  geom_col(aes(x = datetime, y = output), color = 'blue') +
  labs(title = 'Total hydro generation, by hour', x = 'Hour', y = 'Hydro output (MW)') + 
  theme_few()

long_gen %>%
  filter(source %in% c('large_hydro', 'small_hydro')) %>%
  group_by(datetime) %>%
  summarize(output = sum(output)) %>%
  ggplot() +
  geom_line(aes(x = datetime, y = output), size = 1.5, col = 'darkred') +
  labs(title = 'Total hydro generation, by hour', x = 'Hour', y = 'Hydro output (MW)') + 
  theme_few()


long_gen %>%
  filter(source %in% c('large_hydro', 'small_hydro')) %>%
  group_by(datetime) %>%
  summarize(output = sum(output)) %>%
  ggplot() +
  geom_area(aes(x = datetime, y = output), size = 1.5, col = 'pink', fill = 'grey') +
  labs(title = 'Total hydro generation, by hour', x = 'Hour', y = 'Hydro output (MW)') + 
  theme_few()

long_gen %>% #standard is 1.5x SD outside mean
  ggplot() + 
  geom_boxplot(aes(x = source, y = output)) + 
  labs(title = 'Amount of energy generated by each source, Sep 3--9', x = 'Source') +
  theme_few()











